
/*
=========================================================
Project Name : Product Revenue Analysis

Objective:
Analyze product sales and identify top-performing
products based on total revenue generated.

Tools Used:
PostgreSQL
SQL

=========================================================
*/


-- =====================================================
-- Create Products Table
-- =====================================================

CREATE TABLE Products (
    ProductID INT PRIMARY KEY,
    ProductName VARCHAR(100),
    Price DECIMAL(10,2)
);


-- =====================================================
-- Insert Product Data
-- =====================================================

INSERT INTO Products (ProductID, ProductName, Price)
VALUES
(1,'Apple',2.50),
(2,'Banana',1.50),
(3,'Orange',3.00),
(4,'Mango',2.00);


-- =====================================================
-- Create Orders Table
-- =====================================================

CREATE TABLE Orders (
    OrderID INT,
    ProductID INT,
    Quantity INT,
    Sales DECIMAL(10,2)
);


-- =====================================================
-- Insert Order Data
-- =====================================================

INSERT INTO Orders (OrderID, ProductID, Quantity, Sales)
VALUES
(1,1,10,25.00),
(2,1,5,12.50),
(3,2,8,12.00),
(4,3,12,36.00),
(5,4,6,12.00);


-- =====================================================
-- Business Question:
-- Calculate the total revenue generated by each product
-- and rank products from highest to lowest revenue.
-- =====================================================

SELECT
    p.ProductName,
    SUM(o.Sales) AS TotalRevenue
FROM Products p
JOIN Orders o
ON p.ProductID = o.ProductID
GROUP BY
    p.ProductName
ORDER BY
    TotalRevenue DESC;